# frozen_string_literal: true

FactoryBot.define do
  factory :media_attachment do
    association :user
    attachment_type { "image" }
    title_i18n { { "en" => "Sample image", "pl" => "Przykładowy obrazek" } }
    alt_text_i18n { { "en" => "A sample alt text", "pl" => "Przykładowy alt" } }
    caption_i18n { { "en" => "Sample caption", "pl" => "Przykładowy podpis" } }
    position { 0 }

    # CarrierWave + MiniMagick + the model's `set_file_metadata` callback all
    # need a real file path, so we materialise the stub bytes into a Tempfile
    # and wrap it in an ActionDispatch::Http::UploadedFile (the same wrapper
    # Rails uses for real multipart uploads).
    file do
      MediaAttachmentFactoryHelpers.uploaded_file_for(attachment_type)
    end

    trait :document do
      attachment_type { "document" }
    end

    trait :video do
      attachment_type { "video" }
    end

    trait :audio do
      attachment_type { "audio" }
    end

    trait :for_post do
      transient do
        post { nil }
      end
      after(:build) do |att, evaluator|
        post_record = evaluator.post || create(:post)
        att.attachable = post_record
      end
    end

    trait :orphan do
      attachable_id { nil }
      attachable_type { nil }
    end
  end
end

# Tiny helpers so the factory does not need a real image on disk for every spec
# that just touches the model. The few specs that actually need a real image
# (e.g. inline-figure rendering) override the `file` attribute with their own
# fixture path.
module MediaAttachmentFactoryHelpers
  module_function

  FIXTURES_DIR = File.expand_path("../fixtures/files", __dir__)

  # Real, on-disk fixtures generated by ImageMagick. Using actual valid
  # PNG / PDF bytes is the only reliable way to satisfy CarrierWave's
  # `process_image` step (`img.strip; img.quality "85"; resize_to_limit`)
  # plus `MiniMagick::Image.open` in the model's `set_file_metadata`.
  def fixture_path_for(type)
    case type
    when "image"    then File.join(FIXTURES_DIR, "sample.png")
    when "document" then File.join(FIXTURES_DIR, "sample.pdf")
    when "video"    then File.join(FIXTURES_DIR, "sample.png") # placeholder
    when "audio"    then File.join(FIXTURES_DIR, "sample.png") # placeholder
    else File.join(FIXTURES_DIR, "sample.png")
    end
  end

  def stub_content_type(type)
    case type
    when "image"    then "image/png"
    when "document" then "application/pdf"
    when "video"    then "video/mp4"
    when "audio"    then "audio/mpeg"
    else "application/octet-stream"
    end
  end

  def stub_filename(type)
    case type
    when "image"    then "sample.png"
    when "document" then "sample.pdf"
    when "video"    then "sample.mp4"
    when "audio"    then "sample.mp3"
    else "sample.bin"
    end
  end

  # Returns a Rack::Test::UploadedFile pointing at the on-disk fixture.
  # Works for both unit specs (model/policy/worker) and request specs
  # going through the multipart layer.
  def uploaded_file_for(type)
    require "rack/test/uploaded_file"
    Rack::Test::UploadedFile.new(
      fixture_path_for(type),
      stub_content_type(type),
      original_filename: stub_filename(type)
    )
  end

  # Backwards-compat alias for specs that referenced the older name.
  def rack_test_uploaded_file_for(type)
    uploaded_file_for(type)
  end
end

FactoryBot::SyntaxRunner.include(MediaAttachmentFactoryHelpers)
